version: '3'
services:
  web:
    image: apply/server
    container_name: web
    command: bash -c "
      while ! nc -z mysql_db 3306; do sleep 1; done 
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn recruiting.wsgi:application -b 0.0.0.0:8000" # 서버 실행
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app
      - ./static:/app/static
    networks:
      - server
    depends_on:
      - mysql_db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./cert/certbot/conf:/etc/letsencrypt # 이 부분
      - ./cert/certbot/www:/var/www/certbot # 이 부분
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" # 이 부분
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - web
    networks:
      - server

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password} # .env에 있는 db_password와 연결
      MYSQL_DATABASE: apply
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3305:3306"
    networks:
      - server

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./cert/certbot/conf:/etc/letsencrypt 
      - ./cert/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  server:

volumes:
  database:
